#修改默认端口为8081
server:
  port: 8081

#设置数据源信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jinqiao
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


#注册映射文件
#设置实体类的别名
mybatis-plus:
  mapper-locations: classpath*:com/jxd/studentmanager/mapper/mapping/*.xml
  type-aliases-package: com.jxd.studentmanager.model