#修改默认端口为8081
server:
  port: 8081

#设置数据源信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jinqiao
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  resources:
    static-locations: file:${web.upload-path}



#注册映射文件
mybatis-plus:
  mapper-locations: classpath*:com/jxd/studentmanager/mapper/mapping/*.xml
  type-aliases-package: com.jxd.studentmanager.model #设置实体类别名
  configuration:
    map-underscore-to-camel-case: false

web:
  upload-path: D:\mygit10\src\main\assests
